env:
  JULIA_VERSION: "1.9.3"

steps:
  - label: "wake up"
    command: echo "the sky is awake, so I'm awake, so we have to play!"

  - label: ":scroll: script!"
    command: "script.sh"

  - wait
  
  - label: "run julia tests"
    command: 
      - "echo $JULIA_DEPOT_PATH"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile'"
      - "julia --project -e 'using Pkg; Pkg.status"
